apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: react-docker
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31003
  selector:
    app: todo